version: '3.9'

services:

  database:
    image: 'postgres:9.6-alpine'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: owt
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  
  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - 5050:5050 

        